Repository despensa-app/despensa-web, pull requests merged in 2024-10, with the labels that each got.

#9 feat: Add PR Size Labeler Github Action
  .github/workflows/labeler.yml
Labels: hacktoberfest-accepted

#10 fixed blank space on the footer
  src/styles.css
Labels: hacktoberfest-accepted

#11 File-Added: Docker compose.yaml
  compose.yaml
Labels: hacktoberfest-accepted

#13 feat: Implement buttons to add product
  src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.html
  src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.ts
Labels: hacktoberfest-accepted

#15 Added lazy loading..
  src/app/app.routes.ts
Labels: hacktoberfest-accepted

#21 Add build file for Github Action
  .github/workflows/build.yml
Labels: Size: Small

#22 deepsource issues
  src/app/modules/shopping-list/layout/header-shopping-list/header-shopping-list.component.ts
  src/app/modules/shopping-list/pages/add-products-shopping-list/add-products-shopping-list.component.ts
  src/app/shared/components/modal-navbar/modal-navbar.component.ts
Labels: hacktoberfest-accepted, Size: Small
